security:
    encoders:
        Tellaw\LeadsFactoryBundle\Entity\Users: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          entity: { class: Tellaw\LeadsFactoryBundle\Entity\Users, property: login }

    firewalls:
        secured_area:
            pattern:    ^/admin
            anonymous: ~
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin/monitoring/dashboard
            logout:
                path:   /admin/logout

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
